# Site settings
title: Cn3ya开发笔记
email: cn3ya@cn3ya.com
description: > # this means to ignore newlines until "baseurl:"
  个人技术博客，关于linux，php，javascript，mysql，apahce，nginx和一些开源软件的技术分享，商业合作和咨询请联系左侧邮箱。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cn3ya.com" # the base hostname & protocol for your site
github_username:  cn3ya
stackoverflow_username: cn3ya
stackoverflow_id: 5305101
# Build settings
markdown: kramdown

#Serve Command Options
host: 0.0.0.0
port: 8000
theme: jekyll-theme-time-machine