# Site settings
title: Cn3ya开发笔记
email: cn3ya@4voxel.com
description: > # this means to ignore newlines until "baseurl:"
  个人技术博客，关于软件技术的分享，商业合作和咨询请联系左侧邮箱。
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  cn3ya
stackoverflow_username: cn3ya
stackoverflow_id: 5305101
# Build settings
markdown: kramdown

#Serve Command Options
host: 0.0.0.0
port: 8000
theme: jekyll-theme-time-machine